### ISSUE TITLE
Problem reusing pre-trained model on different machine

### ISSUE THREAD

**Issue by diegoje** [charlesashby/CharLSTM#7]
Hi Charles, great code! I've been having a lot of fun with it and the training/prediction worked well when done on an EC2 instance. 

I then tried copying the checkpoints to run a prediction on my local machine, with the same environment, and I get the following error:

```
(testenv) MBP-Diego:DeepLearning diego$ python main.py lstm --sentences 'life is beautiful'
Using model: lstm
Training: False
processing sentence: life is beautiful
Loading model /tmp/checkpoints/lstm...
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    network.predict_sentences(args.sentences)
  File "/private/tmp/DeepLearning/lib_model/char_lstm.py", line 292, in predict_sentences
    saver.restore(sess, SAVE_PATH)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,134,25] rhs shape= [1,1,109,25]
	 [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@TDNN/kernel_1/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](TDNN/kernel_1/w, save/RestoreV2_7)]]

Caused by op u'save/Assign_7', defined at:
  File "main.py", line 25, in <module>
    network.predict_sentences(args.sentences)
  File "/private/tmp/DeepLearning/lib_model/char_lstm.py", line 288, in predict_sentences
    saver = tf.train.Saver()
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/private/tmp/testenv/testenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,134,25] rhs shape= [1,1,109,25]
	 [[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@TDNN/kernel_1/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](TDNN/kernel_1/w, save/RestoreV2_7)]]
```

Am I making a mistake by copying the checkpoints or is it a problem in the way checkpoints are saved/restored? 

Thanks!

**Comment by charlesashby** [comment]
Hello Diego! Are you sure you used the CPU version for training the model and getting the checkpoint? I think saving a model using GPU and then trying to predict using CPU can cause that kind of problem.. but I'll need to check!

**Comment by diegoje** [comment]
Hi Charles! I’m using CPUs for both - so it shouldn’t interfere.

- Cloud: a c4.xlarge EC2 instance
- Local: Macbook i5

I have also tested using your checkpoints and I get the same error:
```
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,7,134,175] rhs shape= [1,7,70,175]
	 [[Node: save/Assign_19 = Assign[T=DT_FLOAT, _class=["loc:@TDNN/kernel_7/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](TDNN/kernel_7/w, save/RestoreV2_19)]]
```

A workaround is to train and use the model on the same machine, but not very practical. I'll let you know if I find a solution!

**Comment by charlesashby** [comment]
Hello Diego! I fixed the issue you can clone the new version now, keep in mind that I only tested it using the GPU version of Tensorflow (`tensorflow-gpu==1.1.0`) I don't know if it will work on CPU!

**Comment by diegoje** [comment]
Thanks Charles - I have tested and it works on CPU using your checkpoints.

Since I tested on CPU, the only change needed was `tensorflow-gpu==1.1.0` to `tensorflow==1.1.0`... Maybe you want to add this to `README.md`?

This means we can train on GPU and predict on CPU - top!

**Comment by charlesashby** [comment]
Sweet, will do, thanks Diego!

**Comment by mmosleh** [comment]
Hi Charles,

I tried to use the pre-train model I keep receiving the following error. I think this is different from the what has been mentioned before.

thanks!

```
$ python main.py lstm --sentence 'test'
Using model: lstm
Training: False
processing sentence: test
/anaconda/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Couldn't import dot_parser, loading of dot files will not be possible.
WARNING:tensorflow:From /anaconda/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-04-04 21:26:18.807132: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/test/CharLSTM-master/entity-sentiment/CharLSTM/checkpoints/lstm...
2018-04-04 21:26:18.838957: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key LSTM/rnn/basic_lstm_cell/bias not found in checkpoint
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    network.predict_sentences(args.sentences)
  File "/CharLSTM-master/entity-sentiment/CharLSTM/lib_model/char_lstm.py", line 290, in predict_sentences
    saver.restore(sess, SAVE_PATH)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1775, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key LSTM/rnn/basic_lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "main.py", line 25, in <module>
    network.predict_sentences(args.sentences)
  File "/CharLSTM-master/entity-sentiment/CharLSTM/lib_model/char_lstm.py", line 286, in predict_sentences
    saver = tf.train.Saver()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1311, in __init__
    self.build()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1357, in _build
    build_save=build_save, build_restore=build_restore)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 809, in _build_internal
    restore_sequentially, reshape)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 448, in _AddRestoreOps
    restore_sequentially)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 860, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1458, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key LSTM/rnn/basic_lstm_cell/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```
